### ISSUE TITLE
Usecase for masthead image per post

### ISSUE THREAD

**Issue by atiq-cs** [statiqdev/CleanBlog#28]
Is there any use case of masthead image per post? If there is none probably having global (one per site) masthead is image enough as specified in `settings.yml` ?

Sorry, putting it here, not sure where else to discuss. This is related to the CleanBlog's implementation of masthead support.

**Comment by atiq-cs** [comment]
cc @rdeago @daveaglick

**Comment by rdeago** [comment]
I have per-post images on my blog. The best part is that they are completely optional: if you want just a site-wide masthead image, you configure just that and you're done. Then if / when you change your mind you can always add (or remove) per-post images later.

By the way, supporting only site-wide images would neither shorten nor simplify the code AFAIK.

**Comment by atiq-cs** [comment]
I know it is optional. However, just trying to get understanding on the use cases. For example, in my blog, I use one global mast head and I use photos inside posts.

Per post images on top of the post, under the post title makes sense IMO.

As per my view, I don't get the meaning of per post mast head image since mast head images are neither quite clearly presented nor complementing the content!

**Comment by daveaglick** [comment]
I suspect this is probably a non-issue because of the way metadata "falls through". As @rdeago pointed out, if you want a site-wide masthead you can define that in the global settings file and it'll trickle down to every page. If you want per-page mastheads, or just want to override the site-wide one for a page or two, you can do that too by defining directly in the page front-matter. The key here is flexibility. I took the position way back at the start of this project that it should present as many options to the user as possible and I shouldn't be making any assumptions about what they do or don't need or want.

I'll close this particular issue since it sounds like we've got it covered - but feel free to ping me to reopen it.
